\mainmatter

```{r, include=FALSE}
knitr::opts_chunk$set(out.width = "100%")
```


# Introduction to Part 1



### Learning Objectives: 
•	Gain a basic understanding of what a GIS is and its relevance to transport studies
•	Know what some of the key data types and file formats
•	Import pre-cleaned vector data into QGIS and navigate basic QGIS features
•	Select a subset of the data
•	Make a map showing point, line and polygon features and export it.  
•	Understand the key cartographic elements that must be present to allow interpretation of a map

### What is included in Part 1?

*	GIS ideas and concepts - we very briefly introduce some key GIS concepts and ideas.  
*	Opening QGIS and key features - We then explain what the main components of QGIS are, explain how to set up a project and save work and what some of the most useful buttons do
*	Downloading and loading data - we show you how to get some data we have prepared for the workshop and load it into QGIS
*	Style and select features - change the way features look on the screen
*	Making maps - Make a map which you can export and include in a document 



