# Further reading


```{r, include=FALSE}
knitr::opts_chunk$set(out.width = "100%")
```


## Learning how to use QGIS 

**This is a recent self learn text.  **

Menke,K. (2019)Discover QGIS 3.x: A Workbook for Classroom or Independent Study (Paperback) Locate Press  ISBN: 9780998547763 


QGIS also has a very detailed web-based user-manual. 
http://docs.qgis.org/2.2/en/docs/user_manual/index.html 


Other books of interest

Graser, A., 2016. Learning QGIS - Third Edition, 3rd Revised edition edition. ed. Packt Publishing.

Taylor, M.M., Freeman, N., 2014. Getting Started With GIS Using QGIS, 1 edition. ed. CreateSpace Independent Publishing Platform.



## GIS text books (covering principles of GIS)  

Ferrari, E., Rae, A, (2019). GIS for Planning and the Built Environment. MacMillan ISBN: 9781137307149

Heywood, D.I., Cornelius, M.S., Carver, D.S., 2011. An Introduction to Geographical Information Systems, 4 edition. ed. Prentice Hall, Harlow, England ; Toronto.

Longley, P.A., Goodchild, M.F., Maguire, D.J., Rhind, D.W., 2015. Geographic Information Science and Systems, 4th Revised edition edition. ed. John Wiley & Sons, Hoboken, NJ.

##	Open online resources
**Further information on GIS concepts**
Geographic Information System Basics : http://2012books.lardbucket.org/books/geographic-information-system-basics/index.html


**Further information on GIS and transport**
http://www.geos.ed.ac.uk/~gisteac/gis_book_abridged/files/ch59.pdf


## How to install QGIS on your own computer

If you cannot access QGIS at work or at an educational establishment, you will need to install it on your computer.

For instructions on installing QGIS, see [download.qgis.org/](https://download.qgis.org/).  


Here you can download QGIS for Windows, Mac and other operating systems.
For most people running Windows, clicking on the [OSGeo4W](http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe) download link and installing this version is recommended.
The OSGeo4W version includes additional features beyond those included in the initial install.  

If you use other operating systems, or want a smaller installation, we recommend the options headed "Long term release repository (most stable)"  


